### ISSUE TITLE
Fix weird synchronization between selected student for demonstration and skill sheets

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#438]
1. Open the **Log Demonstration** window
2. Select a student
3. Open two or more skill sheets
4. Clear the student selection
  - [x] Active skill sheet clears but doesn't revert back to "select student" placeholder
5. Switch to another skill sheet
  - [x] Prior student selection form demonstration gets restored
    - This is weird, there shouldn't be any mechanism for this
    - All skill sheets should get wiped immediately when student is cleared

## TODO

- [x] Use `select` event instead of `change` event for propagating student selector to ratings field

**Comment by ckunkel** [comment]
The "Select Student" placeholder does show when you clear the selected student, but #5 still occurs (prior student restored) when you do anything other than select another student.

**Comment by themightychris** [comment]
So this issue was caused by the student selector providing a button for clearing the selection while the underlying data model would reject having no student selected as invalid and revert it. My solution was to remove the "clear" button from the student selector which appears to be in effect on cbl-qa, but I see now that you can still temporarily "clear" the selected student by deleting or typing in the field.

I plan to address this by changing the behavior of the student selector to apply itself only when you select a matching student rather than as you type.

**Comment by themightychris** [comment]
@ckunkel the issues with the ratings field changing while you type in the student selector is fixed in 786fb78b93f17fd65001928f33f53441a3bfe24f and is getting pushed to cbl-qa now
